name: Test Python Tk
on:
  push:
    branches:
      - tcl-tk
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-latest-large]
        # python-version: ["3.8.10", "3.8.17", "3.9.1", "3.9.19", "3.9.19", "3.10.1", "3.10.14", "3.11.9"]
        python-version: [ "3.10.16"]

      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # uses: actions/setup-python@v5
        # uses: priya-kinthali/setup-python@test-930
        uses: priya-kinthali/setup-python@test-tcl
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Print Tcl/Tk version
      #   run: |
      #     tclsh <<< 'puts [info patchlevel]; exit'
      #     wish <<< 'puts [info patchlevel]; exit'
      - name: Verify Python Tk Version
        run: |
          python -c "import tkinter; print(f'Tkinter TkVersion: {tkinter.TkVersion}')"
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Run tk script (closes itself after 5 seconds) - Ubuntu
        if: runner.os == 'Linux'
        run: xvfb-run python tk_min.py
      - name: Run tk script (closes itself after 5 seconds)
        if: runner.os != 'Linux'
        run: python tk_min.py
