jobs:
- job: Build_Python
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: $(VmImage)
  steps:
  - checkout: self
    submodules: true

# We need this temporary step to have a consistent version of PowerShell on all images.
  - task: PowerShell@2
    displayName: 'Update PowerShell version for macOS'
    condition: eq(variables['Platform'], 'darwin')
    inputs:
      TargetType: inline
      script: |
        brew update
        brew upgrade --cask powershell

  - task: PowerShell@2
    displayName: 'Build Python $(VERSION)'
    inputs:
      targetType: filePath
      filePath: './builders/build-python.ps1'
      arguments: '-Version $(VERSION) -Platform $(Platform) -Architecture $(Architecture)'
      pwsh: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Python $(VERSION)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'python-$(VERSION)-$(Platform)-$(Architecture)'