name: $(date:yyyyMMdd)$(rev:.r)-Python-$(VERSION)
trigger: none
pr: none

stages:
- stage: Build_Python_MacOS
  dependsOn: []
  variables:
    VmImage: 'macOS-10.15'
    Platform: darwin
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Python_MacOS
  condition: succeeded()
  dependsOn: Build_Python_MacOS
  variables:
    VmImage: 'macOS-10.15'
    Platform: darwin
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Python_Ubuntu_1804
  dependsOn: []
  variables:
    VmImage: 'ubuntu-18.04'
    Platform: linux-18.04
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Python_Ubuntu_1804
  condition: succeeded()
  dependsOn: Build_Python_Ubuntu_1804
  variables:
    VmImage: 'ubuntu-18.04'
    Platform: linux-18.04
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Python_Ubuntu_2004
  dependsOn: []
  variables:
    VmImage: 'ubuntu-20.04'
    Platform: linux-20.04
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Python_Ubuntu_2004
  condition: succeeded()
  dependsOn: Build_Python_Ubuntu_2004
  variables:
    VmImage: 'ubuntu-20.04'
    Platform: linux-20.04
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Python_X64_Windows
  dependsOn: []
  variables:
    VmImage: 'vs2017-win2016'
    Platform: win32
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Python_x64_Windows
  condition: succeeded()
  dependsOn: Build_Python_X64_Windows
  variables:
    VmImage: 'vs2017-win2016'
    Platform: win32
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Python_x86_Windows
  dependsOn: []
  variables:
    VmImage: 'vs2017-win2016'
    Platform: win32
    Architecture: x86
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Python_x86_Windows
  condition: succeeded()
  dependsOn: Build_Python_x86_Windows
  variables:
    VmImage: 'vs2017-win2016'
    Platform: win32
    Architecture: x86
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Publish_Release
  dependsOn: [Test_Python_MacOS, Test_Python_Ubuntu_1804, Test_Python_Ubuntu_2004, Test_Python_x64_Windows, Test_Python_x86_Windows]
  jobs:
  - deployment: Publish_Release
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    environment: 'Get Available Tools Versions - Publishing Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /azure-pipelines/templates/publish-release-steps.yml
